image: git.hannay.de:4567/hannayk/rezepte/rust-agent:nightly

stages:
  - init
  - build
  - test

init:
  stage: init
  script:
    - cargo --version
    - rustc --version

build:
  stage: build
  script:
    - cargo build

test:
  stage: test
  script:
    - cargo test
