image: git.hannay.de:4567/hannayk/rezepte/rust-agent:nightly

stages:
  - init
  - lint
  - build
  - test

init:
  stage: init
  script:
    - cargo --version
    - rustc --version

lint:
  stage: lint
  script:
    - cargo clippy

build:
  stage: build
  script:
    - cargo build

test:
  stage: test
  script:
    - cargo test
