image: git.hannay.de:4567/hannayk/rezepte/rust-agent:nightly

stages:
  - init
  - lint
  - build
  - test
  - release
  - deploy

init:
  stage: init
  script:
    - cargo --version
    - rustc --version

lint:
  stage: lint
  script:
    - cargo clippy -- -D warnings

build:
  stage: build
  script:
    - cargo build

test:
  stage: test
  script:
    - echo "cargo test"

release:
  stage: release
  script:
    - cargo build --release
    - cp target/release/recipes .
  artifacts:
    paths:
      - recipes

deploy:
  stage: deploy
  dependencies:
    - release
  script:
    - mkdir -p ~/.ssh && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - chmod 600 $SSH_KEY
    - ls -l
    - scp -i $SSH_KEY -P2022 -r recipes templates recipes.service gitlab-ci@hh-nas.hannay.de:/opt/recipes/
