image: git.hannay.de:4567/hannayk/rezepte/rust-agent:nightly

stages:
  - init
  - lint
  - build
  - test
  - release

init:
  stage: init
  script:
    - cargo --version
    - rustc --version

lint:
  stage: lint
  script:
    - cargo clippy -- -D warnings

build:
  stage: build
  script:
    - cargo build

test:
  stage: test
  script:
    - cargo test

release:
  stage: release
  script:
    - cargo build --release
    - cp target/release/recipes .
  artifacts:
    paths:
      - recipes
      - templates
      - recipes.service
