image: git.hannay.de:4567/hannayk/rezepte/rust-agent:nightly

# DinD service is required for Testcontainers
services:
  - docker:dind

variables:
  # Instruct Testcontainers to use the daemon of DinD.
  DOCKER_HOST: "tcp://docker:2375"
  # Improve performance with overlayfs.
  DOCKER_DRIVER: overlay2

stages:
  - init
  - build
  - test

init:
  stage: init
  script:
    - cargo --version
    - rustc --version

build:
  stage: build
  script:
    - cargo build

test:
  stage: test
  script:
    - cargo test
